# Generated by Django 5.0.3 on 2024-03-19 18:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_alter_cardriver_car_alter_cardriver_driver'),
        ('employees', '0004_alter_car_status'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('place_from', models.CharField(max_length=100, verbose_name='Откуда')),
                ('place_to', models.CharField(max_length=100, verbose_name='Куда')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 19, 18, 2, 55, 320155, tzinfo=datetime.timezone.utc))),
                ('order_date', models.DateTimeField(verbose_name='Дата и время поездки')),
                ('comment', models.TextField(verbose_name='Комментарии')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.car')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.client', verbose_name='Клиент')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.driver', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
