# Generated by Django 5.0.3 on 2024-03-05 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_cardriver'),
        ('employees', '0004_alter_car_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardriver',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.car', unique=True),
        ),
        migrations.AlterField(
            model_name='cardriver',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver', unique=True, verbose_name='Driver'),
        ),
    ]
